resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [active]
    my-vm ansible_host=${yandex_compute_instance.vm-1.network_interface.0.nat_ip_address} ansible_user=stas ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
    DOC
  filename = "ansible/inventory"

  depends_on = [
    yandex_compute_instance.vm-1
  ]
}